# Generated by Django 3.2.8 on 2022-11-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20221110_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='pic4',
            new_name='pic',
        ),
    ]
