# Generated by Django 3.2.8 on 2022-11-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='product',
        ),
    ]
